### ISSUE TITLE
Regarding the version number and accuracy rate issues

### ISSUE THREAD

**Issue by tarimren-admin** [SmileYzn/AccuracyFix#14]
I'm sorry, my English is very poor. I hope I can express myself clearly.
First, after deploying the latest accuracyfix 1.0.9 on the server, the meta list shows version 1.0.7.
Second, after loading accuracyfix on the server, the Desert Eagle's accuracy is surprisingly high. Is this normal?

**Comment by SmileYzn** [comment]
1. Updated version to 1.1.0
2. Yes, this is the purpose of the plugin!

:pray:
