### ISSUE TITLE
Regamedll file needs..

### ISSUE THREAD

**Issue by Escap3d** [SmileYzn/AccuracyFix#16]
Smiley sorry bro its not accuracy topic related talk but i need regamedll new action build.. because i am dont know how to compile file in linux version..

Thanks

**Comment by KnightRider227** [comment]
The compiled file is already available! No need to compile it yourself. Just download linux32 or win32 (depending on your needs) from the "actions build" section.

**Comment by Escap3d** [comment]
> The compiled file is already available! No need to compile it yourself. Just download linux32 or win32 (depending on your needs) from the "actions build" section.

I want cs.so file that is regamedll file i am no need accuracy file

**Comment by SmileYzn** [comment]
![image](https://github.com/SmileYzn/AccuracyFix/assets/5851851/0ffccef5-110e-442e-b4dd-27c3baf219c6)

Again, pay attention to readme.md of that repository.

Make sure that you have latest ReHLDS and ReGameD_CS versions installed on server.
To do this, go to latest action builds of each project and download files.


I just can't support that issues out of scope of Accuracy Fix Plugin!
