### ISSUE TITLE
wrong reapi version !

### ISSUE THREAD

**Issue by Escap3d** [SmileYzn/AccuracyFix#17]
[ 7] ReAPI            RUN   -    reapi_amxx_i386.so        v5.26.0.322-dev  pl1  ANY   Never

![Screenshot 2024-06-18 091653](https://github.com/SmileYzn/AccuracyFix/assets/78939962/12f6afd7-5fd8-487c-8b75-b970b30b1558)

**Comment by SmileYzn** [comment]
This Metamod plugin do not need usage of reapi of amxmodx.
Make sure that ReHLDS and ReGameDLL_CS are updated according readme.md instructions.
