### ISSUE TITLE
Compatibility issues

### ISSUE THREAD

**Issue by drakin003** [SmileYzn/AccuracyFix#19]
## I'm encountering errors related to ReGameDLL version incompatibility. It seems version 26 is no longer supported ##

`[AF] ReGameDLL API minor version mismatch; expected at least 27, real 26`
`[AF] Please update the ReGameDLL up to a minor version API >= 27`

I'm using AMX Mod X 1.8.2-beta65 for compatibility with older plugins that break with AMX 1.9 or 1.10.
Unfortunately, the newer ReGameDLL v27 crashes with AMX 1.8.2-beta65 whenever a player joins the server.

latest AccuracyFix version seems to be running on regamedll v26 but I don't know if its working currently or not(i don't think it is), some functions might be broken

>  [ 1] AMX Mod X        RUN   -    amxmodx_mm_i386.so        v1.8.2           ini  Start ANY  
 [ 2] Reunion          RUN   -    reunion_mm_i386.so        v0.1.0.137       ini  Start Never
 [ 3] VoiceTranscoder  RUN   -    VoiceTranscoder.so        v2017RC5         ini  ANY   ANY  
 [ 4] WHBlocker        RUN   -    whblocker_mm_i386.so      v1.5.697         ini  Chlvl ANY  
 [ 5] HitBox Fix       RUN   -    hitbox_fix_mm_i386.so     v1.1.5           ini  Start ANY  
 [ 6] Accuracy Fix     RUN   -    accuracyfix_mm.so         v1.1.0           ini  ANY   ANY  
 [ 7] ReAPI            RUN   -    reapi_amxx_i386.so        v5.26.0.322-dev  pl1  ANY   Never
 [ 8] Engine           RUN   -    engine_amxx_i386.so       v1.8.2           pl1  ANY   ANY  
 [ 9] MySQL            RUN   -    mysql_amxx_i386.so        v1.8.2           pl1  ANY   ANY  
 [10] CStrike          RUN   -    cstrike_amxx_i386.so      v1.8.2           pl1  ANY   ANY  
 [11] Fun              RUN   -    fun_amxx_i386.so          v1.8.2           pl1  ANY   ANY  
 [12] FakeMeta         RUN   -    fakemeta_amxx_i386.so     v1.8.2           pl1  ANY   ANY  
 [13] Ham Sandwich     RUN   -    hamsandwich_amxx_i386.so  v1.8.2           pl1  ANY   ANY   
 [14] CSX              RUN   -    csx_amxx_i386.so          v1.8.2           pl1  ANY   ANY  
14 plugins, 14 running

Currently, I'm forced to stick with the older, unsupported ReGameDLL version (v26) to maintain compatibility with my plugins. I can't not upgrade the version to regamedll v27  is there's fix for this or do i really have to upgrade to v27

and I think the spray functionality might be broken in the newer Accuracy Fix since shots aren't registering when I spray.

some basic info you might need:

ReGameDLL:
> ReGameDLL version: 5.27.0.716-dev (AMX crashing in this version)
ReGameDLL version: 5.26.0.668-dev (working fine in this version)

AMX:
>AMX Mod X 1.8.2
Compiled: Feb 14 2013, 02:37:31
Build ID: 1.8.2 65:59c21e07b2a6
Core mode: JIT+ASM32

ReHLDS:
>Protocol version 48
Exe version 1.1.2.7/Stdio (cstrike)
ReHLDS version: 3.14.0.833-dev
Build date: 12:16:38 May 30 2024 (3701)

**Comment by KnightRider227** [comment]
Yeah the spray seems off in the new version

**Comment by SmileYzn** [comment]
I just use same ReGameDLL_CS api version of reapi module to amxmodx.

And is not possible revert to API version 26.
You really need to update amxmodx install

Ps. I will try to fix new reapi

**Comment by drakin003** [comment]
> I just use same ReGameDLL_CS api version of reapi module to amxmodx.
> 
> And is not possible revert to API version 26. You really need to update amxmodx install
> 
> Ps. I will try to fix new reapi

How is the new version of AccuracyFix running on regamedll v26 when it requires v27? Shouldn't it crash or something?

**Comment by drakin003** [comment]
changing to same version helped! now shots feel smoother

**Comment by SmileYzn** [comment]
ReGameDLL version: 5.27.0.716-dev (AMX crashing in this version)
ReGameDLL version: 5.26.0.668-dev (working fine in this version)


That amxx crashes in 27 while in 26 works.

The accuracy fix only requires API 27 and throw an error if an older API found, but still try to run hlds.

If crashes or not just depends what functions are used, that is a just simple plugin that recalculate trace line function.

Use accuracy fix at API 26 instead of 27 is at you won risk

**Comment by drakin003** [comment]
> ReGameDLL version: 5.27.0.716-dev (AMX crashing in this version) ReGameDLL version: 5.26.0.668-dev (working fine in this version)
> 
> That amxx crashes in 27 while in 26 works.
> 
> The accuracy fix only requires API 27 and throw an error if an older API found, but still try to run hlds.
> 
> If crashes or not just depends what functions are used, that is a just simple plugin that recalculate trace line function.
> 
> Use accuracy fix at API 26 instead of 27 is at you own risk
> 
> Ps. I made a new build with fixed function

Thanks for doing that, i guess in the end regamedll dev have to add AMX 1.8.2 compatibility in regamedll v27

i will give you update about bullets not registering when spraying(onetaps work just fine)

**Comment by drakin003** [comment]
also in meta info it says that this plugin has no cvars? is this normal?

>name: Accuracy Fix
         desc: Accuracy Fix
       status: running
       action: none
     filename: addons/accuracyfix/dlls/accuracyfix_mm.so
         file: accuracyfix_mm.so
     pathname: /home/drakin/cs/cstrike/addons/accuracyfix/dlls/accuracyfix_mm.so
        index: 6
       source: ini file
     loadable: at any time
   unloadable: at any time
      version: 1.1.0
         date: Jun 18 2024
       author: SmileY
          url: https://pugbr.net
       logtag: AF
       ifvers: 5:13
  last loaded: Tue Jun 18 19:53:39 2024
DLLAPI functions:
0 functions (DLLAPI)
DLLAPI Post functions:
   ServerActivate_Post
   CmdEnd_Post
2 functions (DLLAPI Post)
No NEWAPI functions.
No NEWAPI Post functions.
Engine functions:
0 functions (Engine)
Engine Post functions:
   TraceLine_Post
1 functions (Engine Post)
Registered commands:
0 commands
Registered cvars:                      float value  string value
0 cvars
No child plugins.

**Comment by KnightRider227** [comment]
You can try AMX version 1.8.3 if AMX 1.9 or 1.10 is making your plugins buggy

**Comment by drakin003** [comment]
I have decided not to use the new version since it has sometimes crashed the server on map change with regamedll v26 and rehlds 3378, along with amx 1.8.2-beta65

i guess regamedll v26 is likely the last version supported by amx 1.8.2-beta65

**Comment by SmileYzn** [comment]
I really want to know what plugin incompatibility you can have with AMXX 1.10.

To be honest AMX Mod X is a outdated software and is not maintained while a new developer assume the GitHub repository.

That is why i decide to code some of my plugins directly as MetaMod plugin.

Finally i need to back to code for CS 1.6 :D

**Comment by drakin003** [comment]
> I really want to know what plugin incompatibility you can have with AMXX 1.10.
> 
> To be honest AMX Mod X is a outdated software and is not maintained while a new developer assume the GitHub repository.
> 
> That is why i decide to code some of my plugins directly as MetaMod plugin.
> 
> Finally i need to back to code for CS 1.6 :D

It's that AutoMix plugin by Pimp, edited version(v1.1.9-f, can't find its source code). I voted in my community between that AutoMix and your MatchBot. I guess people don't want an upgrade.
