### ISSUE TITLE
lagging !

### ISSUE THREAD

**Issue by Escap3d** [SmileYzn/AccuracyFix#2]
i am checking the server then i shoting brust and i see lagging shotting recoil;;

this issue was new action update plzz fix it

**Comment by SmileYzn** [comment]
This is not a issue!
Server can lag by a lot other factors than accuracy fix!!

**Comment by Escap3d** [comment]
> This is not a issue! Server can lag by a lot other factors than accuracy fix!!

bro i check enable and disabled in metamod to much lag in shotting u can check it bro i dont lie

**Comment by Escap3d** [comment]
https://github.com/SmileYzn/AccuracyFix/actions/runs/5190850480 


its action build are ok and then new update are not ok for smooth shooting

**Comment by SmileYzn** [comment]
> > This is not a issue! Server can lag by a lot other factors than accuracy fix!!
> 
> bro i check enable and disabled in metamod to much lag in shotting u can check it bro i dont lie

I'm not telling that you lie. But i have a server with 14 slots and runs perfectly without lags.
Wihtout any thecnical details how the server is configured, is har do classify as bug.

I did not have an crystal ball!

Did you can post more details about bugs? 

Than simple say that is not working or have bug, you always do that here and in any other repositores without provide more information.



> https://github.com/SmileYzn/AccuracyFix/actions/runs/5190850480
> 
> its action build are ok and then new update are not ok for smooth shooting

See? You do it in a repply again, Define smooth shooting? 
Again, will not consider any bug without details or something else

**Comment by Escap3d** [comment]
> > > This is not a issue! Server can lag by a lot other factors than accuracy fix!!
> > 
> > 
> > bro i check enable and disabled in metamod to much lag in shotting u can check it bro i dont lie
> 
> I'm not telling that you lie. But i have a server with 14 slots and runs perfectly without lags. Without any technical details how the server is configured, is hard do classify as bug.
> 
> I did not have an crystal ball!
> 
> Did you can post more details about bugs?
> 
> Than simple say that is not working or have bug, you always do that here and in any other repositores without provide more information.
> 
> > https://github.com/SmileYzn/AccuracyFix/actions/runs/5190850480
> > its action build are ok and then new update are not ok for smooth shooting
> 
> See? You do it in a reply again, Define smooth shooting? Again, will not consider any bug without details or something else.
> 
> Please always provide more details, i really appreciate the feedbacks and issue reports. But i need more details about things, i just can't test everything that is related to any project alone and expect that other people will give same experience as me always.
> 
> Thanks for testing and reporting things!

i have a video w8

**Comment by Escap3d** [comment]
before enabaled and after disbaled u can check full video.. video is to much noise u can mute and check brust shooting...


https://www.mediafire.com/file/mu3fwlahf9rz1ha/2023-06-13+22-08-05.mp4/file

**Comment by Escap3d** [comment]
> FPS and ping not change, no loss or choke.
> Why it is lagging in this case?

I dont know but ur new action build issue check ir clearly plz 🥹
