### ISSUE TITLE
Failed to find memloc for regcvar

### ISSUE THREAD

**Issue by EVOLCORE** [SmileYzn/AccuracyFix#20]
![image](https://github.com/SmileYzn/AccuracyFix/assets/42657432/d55b4bc3-3ccc-4278-9718-b02c33083dd8)

Lastest build from release

**Comment by drakin003** [comment]
are you using latest ReHLDS and ReGameDLL from action build? if not please do that and try again

**Comment by SmileYzn** [comment]
That is a know bug of metamod If i remember. 

Cvars data already are stored on a container, it do not need an memloc.

Already discussed in allied modders forums here 

https://forums.alliedmods.net/showthread.php?s=30102245bb7d7bb3ae8e6ec4d90f23c7&p=714726#post714726
