### ISSUE TITLE
 ReHLDS API minor version mismatch; expected at least 14, real 13

### ISSUE THREAD

**Issue by laimiukas3** [SmileYzn/AccuracyFix#21]
Hello gentlemen, I received the following message when the server start why ?

`[AF] ReHLDS API minor version mismatch; expected at least 14, real 13
[AF] Please update the ReHLDS up to a minor version API >= 14
[AF] ReGameDLL API minor version mismatch; expected at least 27, real 26
[AF] Please update the ReGameDLL up to a minor version API >= 27

game version
ReGameDLL version: 5.26.0.668-dev
version
ReHLDS version: 3.13.0.788-dev`

do i have to use dev-builds ?

**Comment by SmileYzn** [comment]
If you want yes, it is just an warning message.
