### ISSUE TITLE
Failed to find memloc for regcvar 

### ISSUE THREAD

**Issue by csoyuncu** [SmileYzn/AccuracyFix#23]
L 07/18/2024 - 00:59:55: [META] WARNING: Failed to find memloc for regcvar 'af_accuracy_all'
L 07/18/2024 - 00:59:55: [META] WARNING: Failed to find memloc for regcvar 'af_distance_all'
L 07/18/2024 - 00:59:55: [META] WARNING: Failed to find memloc for regcvar 'af_recoil_all'
L 07/18/2024 - 00:59:55: [META] WARNING: Failed to find memloc for regcvar 'af_distance_weapon_p228'
L 07/18/2024 - 00:59:55: [META] WARNING: Failed to find memloc for regcvar 'af_accuracy_weapon_p228'
L 07/18/2024 - 00:59:55: [META] WARNING: Failed to find memloc for regcvar 'af_recoil_weapon_p228'
L 07/18/2024 - 00:59:55: [META] WARNING: Failed to find memloc for regcvar 'af_distance_weapon_glock'
L 07/18/2024 - 00:59:55: [META] WARNING: Failed to find memloc for regcvar 'af_accuracy_weapon_glock'
L 07/18/2024 - 00:59:55: [META] WARNING: Failed to find memloc for regcvar 'af_recoil_weapon_glock'
L 07/18/2024 - 00:59:55: [META] WARNING: Failed to find memloc for regcvar 'af_distance_weapon_scout'
L 07/18/2024 - 00:59:55: [META] WARNING: Failed to find memloc for regcvar 'af_accuracy_weapon_scout'
L 07/18/2024 - 00:59:55: [META] WARNING: Failed to find memloc for regcvar 'af_recoil_weapon_scout'
L 07/18/2024 - 00:59:55: [META] WARNING: Failed to find memloc for regcvar 'af_distance_weapon_xm1014'
L 07/18/2024 - 00:59:55: [META] WARNING: Failed to find memloc for regcvar 'af_accuracy_weapon_xm1014'
L 07/18/2024 - 00:59:55: [META] WARNING: Failed to find memloc for regcvar 'af_recoil_weapon_xm1014'
L 07/18/2024 - 00:59:55: [META] WARNING: Failed to find memloc for regcvar 'af_distance_weapon_mac10'
L 07/18/2024 - 00:59:55: [META] WARNING: Failed to find memloc for regcvar 'af_accuracy_weapon_mac10'
L 07/18/2024 - 00:59:55: [META] WARNING: Failed to find memloc for regcvar 'af_recoil_weapon_mac10'
L 07/18/2024 - 00:59:55: [META] WARNING: Failed to find memloc for regcvar 'af_distance_weapon_aug'
L 07/18/2024 - 00:59:55: [META] WARNING: Failed to find memloc for regcvar 'af_accuracy_weapon_aug'
L 07/18/2024 - 00:59:55: [META] WARNING: Failed to find memloc for regcvar 'af_recoil_weapon_aug'
L 07/18/2024 - 00:59:55: [META] WARNING: Failed to find memloc for regcvar 'af_distance_weapon_elite'
L 07/18/2024 - 00:59:55: [META] WARNING: Failed to find memloc for regcvar 'af_accuracy_weapon_elite'
L 07/18/2024 - 00:59:55: [META] WARNING: Failed to find memloc for regcvar 'af_recoil_weapon_elite'
L 07/18/2024 - 00:59:55: [META] WARNING: Failed to find memloc for regcvar 'af_distance_weapon_fiveseven'

**Comment by SmileYzn** [comment]
Already explained here: 

https://github.com/SmileYzn/AccuracyFix/issues/20
