### ISSUE TITLE
<accuracyfix_mm.so>  badf load  accuracyfix_mm.so

### ISSUE THREAD

**Issue by Brazzabro** [SmileYzn/AccuracyFix#27]
starting with AccuracyFix version 1.1.2 the module stopped loading
<accuracyfix_mm.so>  badf load  accuracyfix_mm.so

Metamod-r v1.3.0.149, API (5:13)
ReHLDS version: 3.14.0.838-dev
ReGameDLL version: 5.27.0.724-dev

**Comment by SmileYzn** [comment]
Update to latest release

**Comment by Brazzabro** [comment]
the problem persists on version 1.1.4

**Comment by SmileYzn** [comment]
![image](https://github.com/user-attachments/assets/af535229-8ff6-4bb8-b9b8-6e12d9af19b8)

Checm plugins.ini in metamod

**Comment by SmileYzn** [comment]
For CS only.

**Comment by Brazzabro** [comment]
[ 1] Accuracy Fix    RUN   -    accuracyfix_mm.so           v1.1.1           ini  ANY   ANY  

version 1.1.1 works, if you replace the accuracyfix_mm.so file, you immediately get an error.
at the same time, plugins.ini in metamod does not change

**Comment by Brazzabro** [comment]
updating GCC to version 4.9 helped solve the problem
