### ISSUE TITLE
click shooting lag!

### ISSUE THREAD

**Issue by Escap3d** [SmileYzn/AccuracyFix#3]
i am add new action build in my server...
i have video and check before enabled and after disabled accuracyfix.... first 2 clicking shoot lag...

https://www.mediafire.com/file/qazju1oev1kvek4/2023-06-14+16-54-18.mp4/file

**Comment by SmileYzn** [comment]
Lag again? Where??
Ping normal, FPS normal, no loss or choke. Where is lagging?

Please describe better what you want. 
That is accuracy fix as plugin name suggest, did you know what is accuracy fix plugin do?

**Comment by Escap3d** [comment]
> Lag again? Where?? Ping normal, FPS normal, no loss or choke. Where is lagging?
> 
> Please describe better what you want. That is accuracy fix as plugin name suggest, did you know what is accuracy fix plugin do?

I dont know why is lagging in clicking plzz check where u missing code no smooth shoting in game u also check on my video before and after accuracy on and off
