### ISSUE TITLE
Расброс

### ISSUE THREAD

**Issue by Alexs12919** [SmileYzn/AccuracyFix#30]
Подскажи как уменьшить разброс оружия к примеру м4а1??? все летит в точку + так же на ходу

Так же _It should be directly compare, is not a bit flag! #18_ данный фикс прировнял стрельбу к ужасной похожу на дефолтную стрельбу!

**Comment by SmileYzn** [comment]
English please

**Comment by Alexs12919** [comment]
Tell me how to reduce the spread of weapons for example m4a1??? everything flies to the point + also on the move

You also need to compare directly, not a bit flag! #18 This fix made the shooting level to terrible, similar to default shooting!

**Comment by SmileYzn** [comment]
Check latest action build, I removed that bitwise check and checked directly the trace flag.

Do not make sense to fix something more than trace bullet

**Comment by Alexs12919** [comment]
I installed this version! but the shooting became worse than standard!

**Comment by SmileYzn** [comment]
See if it comes back to work, is some issue as related here:

https://github.com/SmileYzn/AccuracyFix/issues/29#issuecomment-2308735352
