### ISSUE TITLE
<accuracyfix_mm>  badf load

### ISSUE THREAD

**Issue by Rojedapapu** [SmileYzn/AccuracyFix#31]
Module doesn't load in the latest version (1.1.4). Version 1.1.1 loads normally

I have the last version of ReHLDS and ReGameDLL and I'm running Linux btw

![Screenshot_1](https://github.com/user-attachments/assets/7459ceba-b43d-479b-884f-fb01797b7148)

**Comment by SmileYzn** [comment]
Post more details about system version, etc

**Comment by Rojedapapu** [comment]
> Or try it here:
> 
> https://github.com/SmileYzn/AccuracyFix/actions/runs/10561871857

Didn't work

> Post more details about system version, etc

- Os version: Ubuntu 22.04 x64
- Game version: beta steam_legacy (idk if this affects it or no)
- Rehlds version: ReHLDS version: 3.13.0.788-dev Build date: 07:36:33 Jul 12 2023 (3378)
- Metamod version: Metamod-r v1.3.0.149, API (5:13) Metamod-r build: 11:31:17 Apr 23 2024
- Regamedll version: ReGameDLL version: 5.26.0.668-dev Build date: 19:02:48 Dec 31 2023
- Using Pterodactyl Panel to run the game, version 1.11.5

I installed a fresh install without amxmodx, just rehlds, regamedll, metamod-r and the plugin and same message "bad load", no error messages about the plugin or anything like that

**Comment by SmileYzn** [comment]
Try to

- Add debuglevel 49 on config.ini ofetamod
- Add -debug and -dev on startup parameters
- add log on on server.cfg

After a server startup try to run meta retry <plugin id> on server console

Ps. Is working here at arch linux, I doubt that is related with accuracy fix, since I did not know how hlds works on Ubuntu anyway 

And finally the plugin was build using GCC 4.8 that solves library issues in very outdated systems like centos 7 Ubuntu 18.04

Did you can post results here?

**Comment by SmileYzn** [comment]
And more one thing, try to update rehlds to last action build and regamedllcs too like you do with accuracy fix 🙏

**Comment by Rojedapapu** [comment]
Ok, I'll do that and let you know the results! 😁

**Comment by bys3zy** [comment]
Tell me how I can upgrade to the required versions if only the versions below are available on github?


[AF] ReHLDS API minor version mismatch; expected at least 14, real 13
[AF] Please update the ReHLDS up to a minor version API >= 14
[AF] ReGameDLL API minor version mismatch; expected at least 27, real 26
[AF] Please update the ReGameDLL up to a minor version API >= 27

![image](https://github.com/user-attachments/assets/10748da6-40c7-4afb-8cf6-d908cfe8f3aa)

Last version githab
[13] rehlds - 3.13.0.788 (https://github.com/dreamstalker/rehlds/releases)
[26] ReGameDLL_CS - 5.26.0.668 (https://github.com/s1lentq/ReGameDLL_CS/releases)

**Comment by bys3zy** [comment]
-_-
![image](https://github.com/user-attachments/assets/c5e925a9-043e-4553-a8b8-8445eeae0e2d)

**Comment by Rojedapapu** [comment]
> Intentar
> 
> * Agregue el nivel de depuración 49 en config.ini deetamod
> * Agregue -debug y -dev en los parámetros de inicio
> * Agregar inicio de sesión en server.cfg
> 
> Después de iniciar un servidor, intente ejecutar meta retry en la consola del servidor
> 
> PD: Estoy trabajando aquí en Arch Linux. Dudo que esté relacionado con la corrección de la precisión, ya que de todos modos no sabía cómo funciona HLD en Ubuntu.
> 
> Y finalmente, el complemento se creó utilizando GCC 4.8 que resuelve problemas de biblioteca en sistemas muy obsoletos como centos 7 Ubuntu 18.04
> 
> ¿Pudiste publicar los resultados aquí?


Back here again. After doing  the steps you provided me, this was the log:

```
L 09/09/2024 - 23:28:47: [META] dll: Updating plugins...
L 09/09/2024 - 23:28:47: [META] (debug:1) Loading plugin '<accuracyfix_mm.so>'
L 09/09/2024 - 23:28:47: [META] ERROR: dll: Failed query plugin '<accuracyfix_mm.so>'; Couldn't open file '/home/container/cstrike/addons/accuracyfix/dlls/accuracyfix_mm.so': /lib/i386-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /home/container/cstrike/addons/accuracyfix/dlls/accuracyfix_mm.so)
L 09/09/2024 - 23:28:47: [META] ERROR: dll: Skipping plugin '<accuracyfix_mm.so>'; couldn't query
L 09/09/2024 - 23:28:47: [META] ERROR: dll: Couldn't close plugin file 'accuracyfix_mm.so': invalid handle
L 09/09/2024 - 23:28:47: [META] dll: Finished updating 1 plugins; kept 0, loaded 0, unloaded 0, reloaded 0, delayed 0
L 09/09/2024 - 23:28:47: [META] dll: Rebuilding callbacks...
L 09/09/2024 - 23:28:47: [META] dll: Callbacks rebuilded.
```

Do you have any idea how to fix this? I ran this command hoping it would fix the error, but nope 
`apt-get update libc6`

**Comment by SmileYzn** [comment]
@Rojedapapu 

I still facing issues to use GCC compiler version 4.8 on github action builds.

**Comment by deniska21233** [comment]
8] <accuracyfix_mm.so>  badf load  accuracyfix_mm.so         v -              ini   -     -  
Хостинг myarena тариф про

**Comment by SmileYzn** [comment]
I have updated projec.
