### ISSUE TITLE
Again oneshot click delay lag…

### ISSUE THREAD

**Issue by Escap3d** [SmileYzn/AccuracyFix#5]
On click shot delay lag plzz fix it…

**Comment by Escap3d** [comment]
Bro one click shot is lagging if u r check it plzz🥲

**Comment by Escap3d** [comment]
@SmileYzn bro why r u ignore my issue .. i am serious not fiz 1 click shot minor lag plzz fix it

**Comment by SmileYzn** [comment]
> @SmileYzn bro why r u ignore my issue .. i am serious not fiz 1 click shot minor lag plzz fix it

As i said in other repository:
I'm a free time programmer in that projects! If you not explain what is that LAG issue i can't help! Did you send the video a time ago, but in really FPS, ping, loss and choke is normal!

Tell me, what is exactly lag thing?

**Comment by Escap3d** [comment]
before enable and after disabled note one click defreance...

https://www.mediafire.com/file/44sxuizhtvy0als/2023-06-27+09-43-13.mp4/file

**Comment by SmileYzn** [comment]
That is exactly fix does! It fixes first shot!!

**Comment by Escap3d** [comment]
> That is exactly fix does! It fixes first shot!!

No bro minor issue have it

**Comment by SmileYzn** [comment]
Check new plugin, i added a settings file that you can adjust all things in plugin :+1:
