### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by deniska21233** [SmileYzn/AccuracyFix#8]
core is truncated: expected core file size >= 143773696, found: 2990080
Cannot access memory at address 0xf7f51974
Cannot access memory at address 0xf7f51970
Failed to read a valid object file image from memory.
Cannot access memory at address 0xf7f51974
Cannot access memory at address 0xf7f51970
debug.cmds:4: Error in sourced command file:
Cannot access memory at address 0xffdaa34c

**Comment by SmileYzn** [comment]
Meta list plugins
Amxx plugins if any
Rehlds version
Reganedll version


Please, give more info

**Comment by deniska21233** [comment]
./hlds_run: строка 255:  3244 Ошибка сегментирования                   (стек памяти сброшен на диск) $HL_CMD
i am use rocky linux 9.3

 [ 1] Reunion       RUN   -    reunion_mm_i386.so        v0.1.0.137       ini  Start Never
 [ 2] Revoice       RUN   -    revoice_plus_mm.so        v2.0.5           ini  ANY   Never
 [ 3] AMX Mod X     RUN   -    amxmodx_mm_i386.so        v1.10.0.5467     ini  Start ANY
 [ 4] Rechecker     RUN   -    rechecker.so              v2.7             ini  Chlvl ANY
 [ 5] ReSemiclip    RUN   -    resemiclip.so             v2.3.9           ini  Chlvl ANY
 [ 6] WHBlocker     RUN   -    whblocker.so              v1.5.697         ini  Chlvl ANY
 [ 7] HitBox Fix    RUN   -    hitbox_fix_mm_i386.so     v1.1.5           ini  Start ANY
 [ 8] ReAPI         RUN   -    reapi_amxx_i386.so        v5.24.0.300-dev  pl3  ANY   Never
 [ 9] CSX           RUN   -    csx_amxx_i386.so          v1.10.0.5467     pl3  ANY   ANY
 [10] Ham Sandwich  RUN   -    hamsandwich_amxx_i386.so  v1.10.0.5467     pl3  ANY   ANY
 [11] CStrike       RUN   -    cstrike_amxx_i386.so      v1.10.0.5467     pl3  ANY   ANY
 [12] FakeMeta      RUN   -    fakemeta_amxx_i386.so     v1.10.0.5467     pl3  ANY   ANY
 [13] Engine        RUN   -    engine_amxx_i386.so       v1.10.0.5467     pl3  ANY   ANY


 [  1] 0   Admin Chat              1.10.0.546  AMXX Dev Team                                      adminchat.a  running
 [  2] 1   Admin Commands          1.10.0.546  AMXX Dev Team                                      admincmd.am  running
 [  3] 2   Anti Flood              1.10.0.546  AMXX Dev Team                                      antiflood.a  running
 [  4] 3   Commands Menu           1.10.0.546  AMXX Dev Team                                      cmdmenu.amx  running
 [  5] 4   Info. Messages          1.10.0.546  AMXX Dev Team                                      imessage.am  running
 [  6] 5   Menus Front-End         1.10.0.546  AMXX Dev Team                                      menufront.a  running
 [  7] 6   Players Menu            1.10.0.546  AMXX Dev Team                                      plmenu.amxx  running
 [  8] 7   Plugin Menu             1.10.0.546  AMXX Dev Team                                      pluginmenu.  running
 [  9] 8   Restrict Weapons        1.10.0.546  AMXX Dev Team                                      restmenu.am  running
 [ 10] 9   Scrolling Message       1.10.0.546  AMXX Dev Team                                      scrollmsg.a  running
 [ 11] 10  Admin Votes             1.10.0.546  AMXX Dev Team                                      adminvote.a  running
 [ 12] 11  CS Misc. Stats          1.10.0.546  AMXX Dev Team                                      miscstats.a  running
 [ 13] 12  CS Stats Logging        1.10.0.546  AMXX Dev Team                                      stats_loggi  running
 [ 14] 13  Stats Configuration     1.10.0.546  AMXX Dev Team                                      statscfg.am  running


Exe build: 17:25:27 Jan 13 2024 (3563)  rehlds fix build
ReGameDLL version: 5.26.0.668-dev

Ubuntu 20.04 works
rocky linux 9.3 no works
fix pls rhel

**Comment by SmileYzn** [comment]
Try this action build with static libgcc and libstdc++

https://github.com/SmileYzn/AccuracyFix/actions/runs/7529592214

**Comment by deniska21233** [comment]
nice
