### ISSUE TITLE
Can't launch plugin

### ISSUE THREAD

**Issue by kobra3** [SmileYzn/AccuracyFix#9]
Im trying to install this too but I get
[AF] Interface CCSEntity API version 'CSENTITY_API_INTERFACE_VERSION002' not found

**Comment by SmileYzn** [comment]
Make sure that rehlds and reganedll are updated.

You can download an action build to test it

**Comment by kobra3** [comment]
I'm actually using the very latest.

version
Protocol version 48
Exe version 1.1.2.7/Stdio (cstrike)
ReHLDS version: 3.13.0.791-dev
Build date: 23:57:15 Aug 31 2023 (3428)
Build from: https://github.com/Giferns/rehlds/commit/10a5066

game version
ReGameDLL version: 5.26.0.668-dev
Build date: 19:02:48 Dec 31 2023
Build from: https://github.com/s1lentq/ReGameDLL_CS/commit/d3c0ec8

**Comment by kobra3** [comment]
It worked with last build from actions
